[x,fs]=audioread('chirp.wav');
x=x(:,1);
Y=fft(x);
Fp1=1200;Fp2=3000;Fs1=1000;Fs2=3200;
As=100;
Ap=1;
wp=[2*pi*Fp1/Ft,2*pi*Fp2/Ft];
ws=[2*pi*Fs1/Ft,2*pi*Fs2/Ft];
[n,wn]=ellipord(wp,ws,Ap,As,'s');
[b,a]=ellip(n,Ap,As,wn,'s');
[B,A]=bilinear(b,a,1);
[h,w]=freqz(B,A);
y=filter(B,A,x);
Y1=fft(y);
n=0:length(x)-1;
figure;
subplot(4,1,1);
plot(x);  grid on;
title( '原语音信号时域波形图' );  
xlabel( '单位' );ylabel( '幅度' );

subplot(4,1,2);plot(y);grid on;
title('带通滤波器滤波后语音信号时域波形');
xlabel('时间');
ylabel('?幅度');
subplot(4,1,3);plot(n,abs(Y));grid on;
title('滤波前语音信号频谱');
xlabel('频率');
ylabel('幅度');
axis([0 1000000 0 5]);
subplot(4,1,4);plot(n,abs(Y1));grid on;
title('滤波后语音信号频谱');
xlabel('频率');
ylabel('幅度');
axis([0 1000000 0 5]);
